apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ include "postgress.fullname" . }}
  labels:
    {{- include "postgress.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgress.selectorLabels" . | nindent 8 }}
    spec:
      containers: 
      - name: postgres-pod
        image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
        ports:
          - containerPort: {{ .Values.port.containerPort }}
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          {{- if eq .Values.env.POSTGRES_HOST_AUTH_METHOD "true" }}
          value: true
          {{- end }}      